<?php $items = $items ?? []; $counts = $counts ?? []; $filters = $filters ?? []; $status = $filters['status'] ?? ''; $query = $filters['q'] ?? ''; ?>
<section class="mx-auto max-w-7xl">
  <header class="cms-header slide-in"><div><p class="eyebrow">Admin CMS</p><h1 class="section-title mt-3">News Comment Moderation</h1><p class="mt-4 max-w-2xl text-base leading-7 text-neutral-600">Tinjau, setujui, tolak, atau hapus komentar pembaca sebelum tampil publik.</p></div></header>
  <section class="admin-card mt-6 p-4 md:p-6" id="admin-comment-list" data-ssr="true">
    <form method="get" action="/admin/comment" class="cms-toolbar"><label class="cms-search"><span class="sr-only">Cari komentar</span><input name="q" value="<?= $e($query) ?>" placeholder="Cari nama, email, berita, atau isi..."></label><select name="status" class="config-input js-admin-custom-select"><option value="">Semua status</option><?php foreach (['pending' => 'Pending', 'approved' => 'Approved', 'rejected' => 'Rejected', 'flagged' => 'Flagged'] as $key => $label): ?><option value="<?= $key ?>" <?= $status === $key ? 'selected' : '' ?>><?= $label ?></option><?php endforeach; ?></select><button class="btn btn-secondary" type="submit">Terapkan</button></form>
    <div class="mt-5 grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><article class="admin-card p-4"><span>Pending</span><strong class="block text-2xl"><?= (int) ($counts['pending'] ?? 0) ?></strong></article><article class="admin-card p-4"><span>Approved</span><strong class="block text-2xl"><?= (int) ($counts['approved'] ?? 0) ?></strong></article><article class="admin-card p-4"><span>Rejected</span><strong class="block text-2xl"><?= (int) ($counts['rejected'] ?? 0) ?></strong></article><article class="admin-card p-4"><span>Flagged</span><strong class="block text-2xl"><?= (int) ($counts['flagged'] ?? 0) ?></strong></article></div>
    <div class="mt-5 grid gap-4" id="comment-list"><?php if ($items === []): ?><div class="rounded-2xl border border-neutral-900/10 bg-white p-8 text-center text-sm text-neutral-500">Tidak ada komentar yang cocok.</div><?php endif; ?><?php foreach ($items as $item): ?><article class="comment-moderation-card" data-comment-id="<?= (int) ($item['id'] ?? 0) ?>"><div class="comment-moderation-main"><div class="flex flex-wrap items-center gap-2 text-xs font-bold text-blue-800"><span><?= $e($item['article'] ?? '') ?></span><span>•</span><span><?= $e($item['date'] ?? '') ?></span></div><h2><?= $e($item['name'] ?? '') ?></h2><p class="text-sm text-neutral-600"><?= $e($item['email'] ?? '') ?></p><?php if (!empty($item['parent_id'])): ?><p class="mt-2 rounded-xl bg-blue-50 px-3 py-2 text-xs font-bold text-blue-900">Balasan untuk <?= $e($item['parent_name'] ?? 'komentar') ?>: “<?= $e($item['parent_excerpt'] ?? '') ?>”</p><?php endif; ?><p class="comment-moderation-text"><?= $e($item['content'] ?? '') ?></p></div><aside class="comment-moderation-side"><span class="comment-status-admin <?= $e(strtolower((string) ($item['status'] ?? 'pending'))) ?>"><?= $e(ucfirst((string) ($item['status'] ?? 'pending'))) ?></span><button class="cms-action edit" data-comment-action="approve" data-id="<?= (int) ($item['id'] ?? 0) ?>">Approve</button><button class="cms-action hold" data-comment-action="reject" data-id="<?= (int) ($item['id'] ?? 0) ?>">Reject</button><button class="cms-action delete" data-comment-action="delete" data-id="<?= (int) ($item['id'] ?? 0) ?>">Delete</button></aside></article><?php endforeach; ?></div>
  </section>
</section>
