<?php

declare(strict_types=1);

// 1. Memanggil sistem utama (bootstrap) agar koneksi Database siap dipake
[$router, $request, $response] = require __DIR__ . '/../bootstrap/app.php';

$db = \App\Core\Database::connection();

echo "Mulai memproses seed 20 data buku & publikasi...\n";

// 2. Daftar 20 Data Dummy Terlengkap untuk GenBI Jambi
$dummyBooks = [
    // --- KATEGORI 1: PEDOMAN BI & ORGANISASI (5 BUKU) ---
    [
        'judul' => 'Pedoman Beasiswa Bank Indonesia Tahun 2026',
        'slug' => 'pedoman-beasiswa-bank-indonesia-2026',
        'file_path' => 'assets/files/pedoman-beasiswa-2026.pdf',
        'file_original_name' => 'Pedoman_Beasiswa_BI_2026.pdf',
        'file_size_bytes' => 2516582,
        'file_mime_type' => 'application/pdf',
        'penulis' => 'Bank Indonesia Kantor Perwakilan Jambi',
        'editor' => 'Divisi SDM GenBI',
        'penerbit' => 'Bank Indonesia',
        'deskripsi' => 'Buku pedoman resmi mengenai persyaratan, hak, kewajiban, serta indeks kinerja pelaksana bagi penerima Beasiswa Bank Indonesia Wilayah Provinsi Jambi Tahun 2026.',
        'sinopsis' => 'Panduan Lengkap Syarat & Tata Kelola Beasiswa Bank Indonesia',
        'foto_cover_buku' => 'https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?auto=format&fit=crop&w=600&q=80',
        'tahun_terbit' => 2026,
        'isbn' => '978-602-1111-01-1',
        'page_count' => 48,
        'kategori' => 'Pedoman BI',
        'status' => 'published',
        'view_count' => 520,
        'download_count' => 412,
    ],
    [
        'judul' => 'Pedoman Tata Kelola Kesekretariatan & Administrasi GenBI',
        'slug' => 'pedoman-tata-kelola-kesekretariatan-administrasi-genbi',
        'file_path' => 'assets/files/pedoman-administrasi-genbi.pdf',
        'file_original_name' => 'Pedoman_Administrasi_GenBI.pdf',
        'file_size_bytes' => 1887436,
        'file_mime_type' => 'application/pdf',
        'penulis' => 'Sekretaris Wilayah GenBI Jambi',
        'editor' => 'Ketua Umum GenBI Jambi',
        'penerbit' => 'GenBI Provinsi Jambi',
        'deskripsi' => 'Standar operasional prosedur penulisan surat menyurat, penyusunan proposal kegiatan, LPJ, serta pengarsipan digital di lingkungan Komisariat dan Wilayah GenBI Jambi.',
        'sinopsis' => 'Standar Operasional Administrasi & Kesekretariatan Organisasi',
        'foto_cover_buku' => 'https://images.unsplash.com/photo-1497633762265-9d179a990aa6?auto=format&fit=crop&w=600&q=80',
        'tahun_terbit' => 2025,
        'isbn' => '978-602-1111-02-8',
        'page_count' => 36,
        'kategori' => 'Pedoman BI',
        'status' => 'published',
        'view_count' => 180,
        'download_count' => 110,
    ],
    [
        'judul' => 'Buku Panduan Kode Etik & Disiplin Anggota GenBI Jambi',
        'slug' => 'buku-panduan-kode-etik-disiplin-anggota-genbi-jambi',
        'file_path' => 'assets/files/kode-etik-genbi.pdf',
        'file_original_name' => 'Kode_Etik_GenBI_Jambi.pdf',
        'file_size_bytes' => 1500000,
        'file_mime_type' => 'application/pdf',
        'penulis' => 'Komisi Disiplin & Pengawas Organisasi',
        'editor' => 'Pembina GenBI',
        'penerbit' => 'GenBI Provinsi Jambi',
        'deskripsi' => 'Aturan perilaku, tata krama berpakaian, pedoman interaksi di media sosial, dan prosedur skoring kedisiplinan (GenBI Point) bagi seluruh anggota aktif.',
        'sinopsis' => 'Pedoman Perilaku & Kedisiplinan Kinerja Anggota',
        'foto_cover_buku' => 'https://images.unsplash.com/photo-1589829085413-56de8ae18c73?auto=format&fit=crop&w=600&q=80',
        'tahun_terbit' => 2025,
        'isbn' => '978-602-1111-03-5',
        'page_count' => 28,
        'kategori' => 'Pedoman BI',
        'status' => 'published',
        'view_count' => 315,
        'download_count' => 200,
    ],
    [
        'judul' => 'Prosedur Tetap Protokoler & Etiket Kegiatan Resmi',
        'slug' => 'prosedur-tetap-protokoler-etiket-kegiatan-resmi',
        'file_path' => 'assets/files/protokoler-kegiatan-resmi.pdf',
        'file_original_name' => 'Protokoler_GenBI_Jambi.pdf',
        'file_size_bytes' => 3200000,
        'file_mime_type' => 'application/pdf',
        'penulis' => 'Divisi Hubungan Masyarakat & Protokoler',
        'editor' => 'Tim Humas BI Jambi',
        'penerbit' => 'Bank Indonesia Kantor Perwakilan Jambi',
        'deskripsi' => 'Panduan bertugas bagi panitia penyambutan, MC resmi, dirigen, dan tim pengiring dalam agenda formal Bank Indonesia dan Pemda Provinsi Jambi.',
        'sinopsis' => 'Standar Protokoler Kegiatan Formal Pimpinan & Mitra Kerja',
        'foto_cover_buku' => 'https://images.unsplash.com/photo-1516321318423-f06f85e504b3?auto=format&fit=crop&w=600&q=80',
        'tahun_terbit' => 2025,
        'isbn' => '978-602-1111-04-2',
        'page_count' => 44,
        'kategori' => 'Pedoman BI',
        'status' => 'published',
        'view_count' => 140,
        'download_count' => 75,
    ],
    [
        'judul' => 'Pedoman Pelaksanaan Program Kerja Punggawa GenBI',
        'slug' => 'pedoman-pelaksanaan-program-kerja-punggawa-genbi',
        'file_path' => 'assets/files/pedoman-proker-punggawa.pdf',
        'file_original_name' => 'Pedoman_Proker_Punggawa.pdf',
        'file_size_bytes' => 2900000,
        'file_mime_type' => 'application/pdf',
        'penulis' => 'Deputi Pengembangan Organisasi',
        'editor' => 'Ketua Wilayah & Komisariat',
        'penerbit' => 'GenBI Provinsi Jambi',
        'deskripsi' => 'Manual book eksekusi program kerja dari tahap persiapan, perencanaan anggaran, kemitraan eksternal, hingga audit evaluasi akhir program.',
        'sinopsis' => 'Panduan Manajemen Proyek & Eksekusi Program Kerja',
        'foto_cover_buku' => 'https://images.unsplash.com/photo-1554415707-c18de3f9f00a?auto=format&fit=crop&w=600&q=80',
        'tahun_terbit' => 2024,
        'isbn' => null,
        'page_count' => 50,
        'kategori' => 'Pedoman BI',
        'status' => 'published',
        'view_count' => 210,
        'download_count' => 150,
    ],

    // --- KATEGORI 2: MAJALAH SUARA GENBI (5 BUKU) ---
    [
        'judul' => 'Majalah Suara GenBI Edisi #14: Energi untuk Negeri',
        'slug' => 'majalah-suara-genbi-edisi-14-energi-untuk-negeri',
        'file_path' => 'assets/files/suara-genbi-14.pdf',
        'file_original_name' => 'Majalah_Suara_GenBI_14.pdf',
        'file_size_bytes' => 14500000,
        'file_mime_type' => 'application/pdf',
        'penulis' => 'Tim Redaksi GenBI Jambi',
        'editor' => 'Pimpinan Redaksi Suara GenBI',
        'penerbit' => 'GenBI Provinsi Jambi',
        'deskripsi' => 'Edisi spesial menyorot kolaborasi pemuda dalam mendukung inklusi keuangan di pedesaan Jambi serta rekam jejak pengabdian GenBI Mengajar.',
        'sinopsis' => 'Wadah Informasi, Inspirasi & Kreativitas Mahasiswa GenBI Jambi',
        'foto_cover_buku' => 'https://images.unsplash.com/photo-1512820790803-83ca734da794?auto=format&fit=crop&w=600&q=80',
        'tahun_terbit' => 2025,
        'isbn' => '977-208-9876-01-4',
        'page_count' => 64,
        'kategori' => 'Majalah',
        'status' => 'published',
        'view_count' => 450,
        'download_count' => 310,
    ],
    [
        'judul' => 'Majalah Suara GenBI Edisi #13: Digitalisasi Budaya & Pariwisata',
        'slug' => 'majalah-suara-genbi-edisi-13-digitalisasi-budaya-pariwisata',
        'file_path' => 'assets/files/suara-genbi-13.pdf',
        'file_original_name' => 'Majalah_Suara_GenBI_13.pdf',
        'file_size_bytes' => 13200000,
        'file_mime_type' => 'application/pdf',
        'penulis' => 'Tim Redaksi GenBI Jambi',
        'editor' => 'Divisi Media & Komunikasi',
        'penerbit' => 'GenBI Provinsi Jambi',
        'deskripsi' => 'Mengangkat warisan budaya Candi Muaro Jambi dan strategi percepatan wisata lokal melalui promosi digital dan pembayaran uang elektronik.',
        'sinopsis' => 'Menghubungkan Warisan Leluhur Jambi dengan Era Digital',
        'foto_cover_buku' => 'https://images.unsplash.com/photo-1495446815901-a7297e633e8d?auto=format&fit=crop&w=600&q=80',
        'tahun_terbit' => 2025,
        'isbn' => '977-208-9876-02-1',
        'page_count' => 60,
        'kategori' => 'Majalah',
        'status' => 'published',
        'view_count' => 390,
        'download_count' => 280,
    ],
    [
        'judul' => 'Majalah Suara GenBI Edisi #12: Pemuda Bugar & Literate',
        'slug' => 'majalah-suara-genbi-edisi-12-pemuda-bugar-literate',
        'file_path' => 'assets/files/suara-genbi-12.pdf',
        'file_original_name' => 'Majalah_Suara_GenBI_12.pdf',
        'file_size_bytes' => 11800000,
        'file_mime_type' => 'application/pdf',
        'penulis' => 'Tim Redaksi GenBI Jambi',
        'editor' => 'Divisi Kesehatan & Olahraga',
        'penerbit' => 'GenBI Provinsi Jambi',
        'deskripsi' => 'Liputan eksklusif Turnamen Olahraga GenBI se-Sumater bagian selatan, serta edukasi kesehatan mental bagi mahasiswa berprestasi di tengah padatnya perkuliahan.',
        'sinopsis' => 'Menjaga Kesejahteraan Mental & Fisik Aktivis Kampus',
        'foto_cover_buku' => 'https://images.unsplash.com/photo-1543002588-bfa74002ed7e?auto=format&fit=crop&w=600&q=80',
        'tahun_terbit' => 2024,
        'isbn' => '977-208-9876-03-8',
        'page_count' => 56,
        'kategori' => 'Majalah',
        'status' => 'published',
        'view_count' => 310,
        'download_count' => 195,
    ],
    [
        'judul' => 'Majalah Suara GenBI Edisi #11: Bangga Cinta Paham Rupiah',
        'slug' => 'majalah-suara-genbi-edisi-11-bangga-cinta-paham-rupiah',
        'file_path' => 'assets/files/suara-genbi-11.pdf',
        'file_original_name' => 'Majalah_Suara_GenBI_11.pdf',
        'file_size_bytes' => 12400000,
        'file_mime_type' => 'application/pdf',
        'penulis' => 'Tim Redaksi GenBI Jambi',
        'editor' => 'Divisi Riset & Edukasi',
        'penerbit' => 'GenBI Provinsi Jambi',
        'deskripsi' => 'Kupas tuntas filosofi desain uang Rupiah Tahun Emisi terbaru dan aksi edukasi CBP Rupiah di pasar tradisional Kota Jambi.',
        'sinopsis' => 'Mengenal Lebih Dalam Makna & Simbolisme Mata Uang Kita',
        'foto_cover_buku' => 'https://images.unsplash.com/photo-1532012197267-da84d127e765?auto=format&fit=crop&w=600&q=80',
        'tahun_terbit' => 2024,
        'isbn' => '977-208-9876-04-5',
        'page_count' => 58,
        'kategori' => 'Majalah',
        'status' => 'published',
        'view_count' => 290,
        'download_count' => 180,
    ],
    [
        'judul' => 'Majalah Suara GenBI Edisi #10: Satu Dekade Mengabdi',
        'slug' => 'majalah-suara-genbi-edisi-10-satu-dekade-mengabdi',
        'file_path' => 'assets/files/suara-genbi-10.pdf',
        'file_original_name' => 'Majalah_Suara_GenBI_10.pdf',
        'file_size_bytes' => 15100000,
        'file_mime_type' => 'application/pdf',
        'penulis' => 'Tim Redaksi GenBI Jambi',
        'editor' => 'Ikatan Alumni GenBI (IkaGenBI)',
        'penerbit' => 'GenBI Provinsi Jambi',
        'deskripsi' => 'Edisi monumental peringatan 10 tahun perjalanan GenBI di Provinsi Jambi, berisikan kisah sukses para alumni dan transformasi organisasi dari tahun ke tahun.',
        'sinopsis' => 'Refleksi Satu Dekade Dedikasi GenBI untuk Bumi Sepucuk Jambi Sembilan Lurah',
        'foto_cover_buku' => 'https://images.unsplash.com/photo-1476275466078-4007374efbbe?auto=format&fit=crop&w=600&q=80',
        'tahun_terbit' => 2023,
        'isbn' => '977-208-9876-05-2',
        'page_count' => 72,
        'kategori' => 'Majalah',
        'status' => 'published',
        'view_count' => 610,
        'download_count' => 490,
    ],

    // --- KATEGORI 3: BULETIN KEBANKSENTRALAN (5 BUKU) ---
    [
        'judul' => 'Buletin Edukasi QRIS: Akselerasi Transaksi UMKM Jambi',
        'slug' => 'buletin-edukasi-qris-akselerasi-transaksi-umkm-jambi',
        'file_path' => 'assets/files/buletin-qris-umkm.pdf',
        'file_original_name' => 'Buletin_QRIS_UMKM.pdf',
        'file_size_bytes' => 4500000,
        'file_mime_type' => 'application/pdf',
        'penulis' => 'Divisi Riset & Kebanksentralan',
        'editor' => 'Tim BI Jambi',
        'penerbit' => 'GenBI Provinsi Jambi',
        'deskripsi' => 'Kajian teknis serta keuntungan penggunaan Quick Response Code Indonesian Standard (QRIS) bagi pedagang UMKM dan merchant lokal di Jambi.',
        'sinopsis' => 'Mendorong Transformasi Ekonomi Digital bagi UMKM Lokal',
        'foto_cover_buku' => 'https://images.unsplash.com/photo-1553729459-efe14ef6055d?auto=format&fit=crop&w=600&q=80',
        'tahun_terbit' => 2025,
        'isbn' => null,
        'page_count' => 24,
        'kategori' => 'Buletin',
        'status' => 'published',
        'view_count' => 230,
        'download_count' => 140,
    ],
    [
        'judul' => 'Buletin Stabilitas Sistem Keuangan & Pengendalian Inflasi Daerah',
        'slug' => 'buletin-stabilitas-sistem-keuangan-pengendalian-inflasi-daerah',
        'file_path' => 'assets/files/buletin-inflasi-jambi.pdf',
        'file_original_name' => 'Buletin_Inflasi_Jambi.pdf',
        'file_size_bytes' => 5100000,
        'file_mime_type' => 'application/pdf',
        'penulis' => 'Divisi Riset & Kebanksentralan',
        'editor' => 'Pengamat Ekonomi Provinsi Jambi',
        'penerbit' => 'GenBI Provinsi Jambi',
        'deskripsi' => 'Ulasan peran Tim Pengendalian Inflasi Daerah (TPID) dan kontribusi pemuda dalam gerakan tanam cabai serta kemandirian pangan rumah tangga.',
        'sinopsis' => 'Peran Pemuda dalam Menjaga Stabilitas Harga & Kemandirian Pangan',
        'foto_cover_buku' => 'https://images.unsplash.com/photo-1460925895917-afdab827c52f?auto=format&fit=crop&w=600&q=80',
        'tahun_terbit' => 2025,
        'isbn' => null,
        'page_count' => 30,
        'kategori' => 'Buletin',
        'status' => 'published',
        'view_count' => 195,
        'download_count' => 110,
    ],
    [
        'judul' => 'Buletin Edukasi Cinta, Bangga, Paham (CBP) Rupiah Kuartal III',
        'slug' => 'buletin-edukasi-cbp-rupiah-kuartal-iii',
        'file_path' => 'assets/files/buletin-cbp-rupiah.pdf',
        'file_original_name' => 'Buletin_CBP_Rupiah.pdf',
        'file_size_bytes' => 3800000,
        'file_mime_type' => 'application/pdf',
        'penulis' => 'Duta Rupiah GenBI Jambi',
        'editor' => 'Divisi Edukasi Masyarakat',
        'penerbit' => 'GenBI Provinsi Jambi',
        'deskripsi' => 'Panduan cara mengenali keaslian uang Rupiah dengan teknik dilihat, diraba, diterawang (3D), serta pentingnya merawat uang kertas ketiak berbelanja.',
        'sinopsis' => 'Menjaga Kehormatan Simbol Kedaulatan Negara RI',
        'foto_cover_buku' => 'https://images.unsplash.com/photo-1526304640581-d334cdbbf45e?auto=format&fit=crop&w=600&q=80',
        'tahun_terbit' => 2024,
        'isbn' => null,
        'page_count' => 20,
        'kategori' => 'Buletin',
        'status' => 'published',
        'view_count' => 175,
        'download_count' => 98,
    ],
    [
        'judul' => 'Buletin Tren Ekonomi Digital & Perlindungan Konsumen Keuangan',
        'slug' => 'buletin-tren-ekonomi-digital-perlindungan-konsumen',
        'file_path' => 'assets/files/buletin-ekonomi-digital.pdf',
        'file_original_name' => 'Buletin_Ekonomi_Digital.pdf',
        'file_size_bytes' => 4200000,
        'file_mime_type' => 'application/pdf',
        'penulis' => 'Divisi Kewirausahaan & Teknologi',
        'editor' => 'Tim Ahli Layanan Konsumen BI',
        'penerbit' => 'GenBI Provinsi Jambi',
        'deskripsi' => 'Edukasi mewaspadai pinjaman online ilegal, judi online, dan scam keuangan digital, lengkap dengan saluran penanganan aduan resmi BI.',
        'sinopsis' => 'Cerdas & Aman Beraktivitas di Era Transaksi Finansial Digital',
        'foto_cover_buku' => 'https://images.unsplash.com/photo-1579621970563-ebec7560ff3e?auto=format&fit=crop&w=600&q=80',
        'tahun_terbit' => 2024,
        'isbn' => null,
        'page_count' => 26,
        'kategori' => 'Buletin',
        'status' => 'published',
        'view_count' => 310,
        'download_count' => 215,
    ],
    [
        'judul' => 'Buletin Potensi Komoditas Ekspor Unggulan Provinsi Jambi',
        'slug' => 'buletin-potensi-komoditas-ekspor-unggulan-jambi',
        'file_path' => 'assets/files/buletin-ekspor-jambi.pdf',
        'file_original_name' => 'Buletin_Ekspor_Jambi.pdf',
        'file_size_bytes' => 4900000,
        'file_mime_type' => 'application/pdf',
        'penulis' => 'Divisi Riset & Kebanksentralan',
        'editor' => 'Dinas Perdagangan & BI Jambi',
        'penerbit' => 'GenBI Provinsi Jambi',
        'deskripsi' => 'Analisis prospek komoditas kopi Kerinci, kayu manis, dan karet alam di pasar global dalam menopang neraca perdagangan Provinsi Jambi.',
        'sinopsis' => 'Membangun Daya Saing Komoditas Lokal di Panggung Global',
        'foto_cover_buku' => 'https://images.unsplash.com/photo-1511174511562-5f7f18b874f8?auto=format&fit=crop&w=600&q=80',
        'tahun_terbit' => 2023,
        'isbn' => null,
        'page_count' => 32,
        'kategori' => 'Buletin',
        'status' => 'published',
        'view_count' => 160,
        'download_count' => 88,
    ],

    // --- KATEGORI 4: BUKU SAKU & MATERI EDUKASI (5 BUKU) ---
    [
        'judul' => 'Buku Saku Kepemimpinan & Manajemen Komunitas',
        'slug' => 'buku-saku-kepemimpinan-manajemen-komunitas',
        'file_path' => 'assets/files/buku-saku-kepemimpinan.pdf',
        'file_original_name' => 'Buku_Saku_Kepemimpinan.pdf',
        'file_size_bytes' => 3670016,
        'file_mime_type' => 'application/pdf',
        'penulis' => 'Deputi Pengembangan SDM',
        'editor' => 'Tim Pengarah GenBI',
        'penerbit' => 'GenBI Provinsi Jambi',
        'deskripsi' => 'Buku saku praktis yang merangkum nilai-nilai kepemimpinan, manajemen waktu, pembentukan mindet kognitif, serta resolusi konflik dalam komando organisasi.',
        'sinopsis' => 'Membentuk Karakter Pemimpin Muda Bermarwah & Berintegritas',
        'foto_cover_buku' => 'https://images.unsplash.com/photo-1507842229356-3a0975714b14?auto=format&fit=crop&w=600&q=80',
        'tahun_terbit' => 2025,
        'isbn' => '978-602-2222-01-5',
        'page_count' => 36,
        'kategori' => 'Materi Edukasi',
        'status' => 'published',
        'view_count' => 410,
        'download_count' => 290,
    ],
    [
        'judul' => 'GenBI Career Guide: Sukses Meniti Dunia Kerja & Profesional',
        'slug' => 'genbi-career-guide-sukses-meniti-dunia-kerja',
        'file_path' => 'assets/files/genbi-career-guide.pdf',
        'file_original_name' => 'GenBI_Career_Guide.pdf',
        'file_size_bytes' => 5452595,
        'file_mime_type' => 'application/pdf',
        'penulis' => 'Divisi Kewirausahaan & Karir',
        'editor' => 'Alumni GenBI Jambi (IkaGenBI)',
        'penerbit' => 'GenBI Provinsi Jambi',
        'deskripsi' => 'Panduan lengkap bagi mahasiswa semester akhir mengenai pembuatan CV ATS-Friendly, teknik personal branding di LinkedIn, dan wawancara berbasis STAR method.',
        'sinopsis' => 'Persiapan Matang Bertransisi dari Bangku Kuliah ke Dunia Kerja',
        'foto_cover_buku' => 'https://images.unsplash.com/photo-1586281380349-632531db7ed4?auto=format&fit=crop&w=600&q=80',
        'tahun_terbit' => 2024,
        'isbn' => '978-602-2222-02-2',
        'page_count' => 42,
        'kategori' => 'Buku Saku',
        'status' => 'published',
        'view_count' => 680,
        'download_count' => 510,
    ],
    [
        'judul' => 'Buku Saku Public Speaking & Master of Ceremony (MC)',
        'slug' => 'buku-saku-public-speaking-master-of-ceremony',
        'file_path' => 'assets/files/buku-saku-public-speaking.pdf',
        'file_original_name' => 'Buku_Saku_Public_Speaking.pdf',
        'file_size_bytes' => 2800000,
        'file_mime_type' => 'application/pdf',
        'penulis' => 'Divisi Hubungan Masyarakat',
        'editor' => 'Praktisi Komunikasi Jambi',
        'penerbit' => 'GenBI Provinsi Jambi',
        'deskripsi' => 'Teknik olah vokal, mengatasi panggung gugup (stage fright), gestur tubuh meyakinkan, serta contoh naskah MC formal dan non-formal.',
        'sinopsis' => 'Kuasai Seni Berbicara Mewujudkan Pesan yang Bertenaga & Menginspirasi',
        'foto_cover_buku' => 'https://images.unsplash.com/photo-1475721027785-f74eccf877e2?auto=format&fit=crop&w=600&q=80',
        'tahun_terbit' => 2024,
        'isbn' => '978-602-2222-03-9',
        'page_count' => 32,
        'kategori' => 'Buku Saku',
        'status' => 'published',
        'view_count' => 340,
        'download_count' => 240,
    ],
    [
        'judul' => 'Panduan Desain Grafis & Manajemen Konten Media Sosial',
        'slug' => 'panduan-desain-grafis-manajemen-konten-media-sosial',
        'file_path' => 'assets/files/panduan-desain-konten.pdf',
        'file_original_name' => 'Panduan_Desain_Konten.pdf',
        'file_size_bytes' => 7500000,
        'file_mime_type' => 'application/pdf',
        'penulis' => 'Divisi Media, Informasi & Teknologi',
        'editor' => 'Creative Director GenBI',
        'penerbit' => 'GenBI Provinsi Jambi',
        'deskripsi' => 'Aturan penggunaan logo GenBI, palet warna resmi, pedoman tipografi, serta strategi copywriting dan penjadwalan tayang di Instagram, TikTok, dan Web.',
        'sinopsis' => 'Standar Visual & Branding Digital GenBI Provinsi Jambi',
        'foto_cover_buku' => 'https://images.unsplash.com/photo-1542744094-3a3122c9b60b?auto=format&fit=crop&w=600&q=80',
        'tahun_terbit' => 2025,
        'isbn' => '978-602-2222-04-6',
        'page_count' => 40,
        'kategori' => 'Materi Edukasi',
        'status' => 'published',
        'view_count' => 420,
        'download_count' => 330,
    ],
    [
        'judul' => 'Modul Edukasi Ekonomi Syariah & Wakaf Produktif di Jambi',
        'slug' => 'modul-edukasi-ekonomi-syariah-wakaf-produktif-jambi',
        'file_path' => 'assets/files/modul-ekonomi-syariah.pdf',
        'file_original_name' => 'Modul_Ekonomi_Syariah.pdf',
        'file_size_bytes' => 6100000,
        'file_mime_type' => 'application/pdf',
        'penulis' => 'Komisariat UIN Sulthan Thaha Saifuddin Jambi',
        'editor' => 'Divisi Riset & Kebanksentralan',
        'penerbit' => 'GenBI Provinsi Jambi',
        'deskripsi' => 'Pembahasan instrumen keuangan syariah, potensi wakaf uang untuk pemberdayaan ekonomi umat, serta peran GenBI dalam festival ekonomi syariah.',
        'sinopsis' => 'Menggerakkan Ekonomi Umat Berbasis Nilai-Nilai Keadilan & Berkelanjutan',
        'foto_cover_buku' => 'https://images.unsplash.com/photo-1524995997946-a1c2e315a42f?auto=format&fit=crop&w=600&q=80',
        'tahun_terbit' => 2024,
        'isbn' => '978-602-2222-05-3',
        'page_count' => 50,
        'kategori' => 'Materi Edukasi',
        'status' => 'published',
        'view_count' => 260,
        'download_count' => 170,
    ],
];

$inserted = 0;

// 3. Loop eksekusi insert secara aman pakai PDO (Mencegah SQL Injection & Duplikasi)
foreach ($dummyBooks as $book) {
    // Cek slug agar jika dijalankan berkali-kali tidak ada duplikat data
    $check = $db->prepare('SELECT buku_id FROM tbl_buku WHERE slug = :slug LIMIT 1');
    $check->execute([':slug' => $book['slug']]);

    if ($check->fetch()) {
        echo " [SKIP] Buku '{$book['judul']}' sudah ada di database.\n";
        continue;
    }

    $stmt = $db->prepare('
        INSERT INTO tbl_buku (
            judul, slug, file_path, file_original_name, file_size_bytes, file_mime_type,
            penulis, editor, penerbit, deskripsi, sinopsis, cover_image, foto_cover_buku,
            tahun_terbit, isbn, page_count, kategori, status, view_count, download_count,
            published_at, created_at, updated_at
        ) VALUES (
            :judul, :slug, :file_path, :file_original_name, :file_size_bytes, :file_mime_type,
            :penulis, :editor, :penerbit, :deskripsi, :sinopsis, :cover_image, :foto_cover_buku,
            :tahun_terbit, :isbn, :page_count, :kategori, :status, :view_count, :download_count,
            NOW(), NOW(), NOW()
        )
    ');

    $stmt->execute([
        ':judul' => $book['judul'],
        ':slug' => $book['slug'],
        ':file_path' => $book['file_path'],
        ':file_original_name' => $book['file_original_name'],
        ':file_size_bytes' => $book['file_size_bytes'],
        ':file_mime_type' => $book['file_mime_type'],
        ':penulis' => $book['penulis'],
        ':editor' => $book['editor'],
        ':penerbit' => $book['penerbit'],
        ':deskripsi' => $book['deskripsi'],
        ':sinopsis' => $book['sinopsis'],
        // Isi kedua kolom cover dengan foto dari Unsplash
        ':cover_image' => $book['foto_cover_buku'],
        ':foto_cover_buku' => $book['foto_cover_buku'],
        ':tahun_terbit' => $book['tahun_terbit'],
        ':isbn' => $book['isbn'],
        ':page_count' => $book['page_count'],
        ':kategori' => $book['kategori'],
        ':status' => $book['status'],
        ':view_count' => $book['view_count'],
        ':download_count' => $book['download_count'],
    ]);

    echo " [+] Sukses menambah: {$book['judul']}\n";
    $inserted++;
}

echo "\n✨ Selesai! Berhasil menyuntikkan {$inserted} data buku ke database Anda.\n";
