<?php

declare(strict_types=1);

require dirname(__DIR__) . '/bootstrap/app.php';

use App\Config\ThemeRegistry;

$target = dirname(__DIR__) . '/public/assets/css/theme.css';
$themes = ThemeRegistry::all();

$blocks = [];
foreach ($themes as $key => $theme) {
    $selector = $key === 'genbi' ? ":root,\nhtml[data-theme=\"genbi\"]" : 'html[data-theme="' . $key . '"]';
    $lines = [];
    foreach ($theme['tokens'] as $token => $value) {
        $lines[] = '  --' . $token . ': ' . $value . ';';
    }

    $legacyAliases = [
        'blue-900' => $theme['tokens']['brand-primary-hover'],
        'blue-800' => $theme['tokens']['brand-primary'],
        'blue-700' => brighten($theme['tokens']['brand-primary'], 18),
        'blue-50' => $theme['tokens']['brand-soft'],
        'cream' => $theme['tokens']['background-default'],
        'stone' => $theme['tokens']['background-muted'],
        'surface-soft' => $theme['tokens']['surface-sunken'],
        'ink' => $theme['tokens']['text-primary'],
    ];

    foreach ($legacyAliases as $token => $value) {
        $lines[] = '  --' . $token . ': ' . $value . ';';
    }

    $blocks[] = $selector . " {\n" . implode("\n", $lines) . "\n}";
}

$css = "/* theme.css - generated by tools/build-theme-css.php. Do not edit by hand. */\n\n" . implode("\n\n", $blocks) . "\n";
file_put_contents($target, $css);
echo "Generated theme CSS at {$target}\n";

function brighten(string $channels, int $amount): string
{
    $parts = array_map('intval', preg_split('/\s+/', trim($channels)) ?: []);
    $parts = array_map(static fn (int $value): int => max(0, min(255, $value + $amount)), $parts);
    return implode(' ', $parts);
}
