<?php
$page = $prototypePage ?? '';
$site = $site ?? [];
$home = is_array($site['home'] ?? null) ? $site['home'] : [];
$slides = is_array($site['heroSlides'] ?? null) ? $site['heroSlides'] : [];
$isSliderEditor = $page === 'slider-add';
$isWhyEditor = in_array($page, ['why-choose-add', 'why_choose-add'], true);
$isFaqEditor = $page === 'faq-add';
$sliderSlot = max(1, min(2, (int) ($_GET['slot'] ?? 1)));
$slide = $slides[$sliderSlot - 1] ?? [];
?>
<section class="mx-auto max-w-7xl" id="admin-prototype-root" data-ssr="true" data-prototype-page="<?= $e($page) ?>">
<?php if ($page === 'language'): ?>
  <header class="cms-header slide-in"><div><p class="eyebrow">Admin CMS</p><h1 class="section-title mt-3">Edit Language Data</h1><p class="mt-4 max-w-2xl text-base leading-7 text-neutral-600">Label teknis dan teks terjemahan tersedia di HTML awal.</p></div><button id="save-language" class="btn btn-primary" type="button">Update Language</button></header>
  <section class="admin-card mt-6 p-4 md:p-6"><div class="rounded-2xl bg-blue-50 p-4 text-sm leading-6 text-blue-950">Bagian ini masih memakai data prototipe; persistence bahasa belum memiliki model backend.</div><div class="language-grid mt-6"><?php foreach ([['home', 'Beranda'], ['about', 'Tentang GenBI'], ['news', 'Berita'], ['event', 'Agenda'], ['contact', 'Kontak']] as [$key, $label]): ?><article class="language-row"><code><?= $e($key) ?></code><div class="language-edit" contenteditable="true" spellcheck="false"><?= $e($label) ?></div></article><?php endforeach; ?></div></section>
<?php elseif ($page === 'slider' || $isSliderEditor): ?>
  <header class="cms-header slide-in"><div><p class="eyebrow">Admin CMS</p><h1 class="section-title mt-3"><?= $isSliderEditor ? 'Edit Slider ' . $sliderSlot : 'View Sliders' ?></h1><p class="mt-4 max-w-2xl text-base leading-7 text-neutral-600">Slider berasal dari settings hero landing page.</p></div><a href="<?= $isSliderEditor ? '/admin/slider' : '/admin/slider-add?slot=1' ?>" class="btn <?= $isSliderEditor ? 'btn-secondary' : 'btn-primary' ?>"><?= $isSliderEditor ? 'View All' : 'Add Slider' ?></a></header>
  <?php if ($isSliderEditor): ?><form class="editor-workspace compact mt-6" id="slider-form" data-slot="<?= $sliderSlot ?>"><main class="block-writing-surface"><label class="config-field"><span>Eyebrow / Badge</span><input class="config-input" id="slider-eyebrow" value="<?= $e($slide['eyebrow'] ?? 'GenBI Provinsi Jambi') ?>"></label><label class="config-field"><span>Heading</span><textarea class="config-input min-h-28" id="slider-heading"><?= $e($slide['title'] ?? '') ?></textarea></label><label class="config-field"><span>Caption</span><textarea class="config-input min-h-32" id="slider-caption"><?= $e($slide['caption'] ?? '') ?></textarea></label></main><aside class="editor-config-sidebar"><section class="config-card"><h2>Slider Config</h2><label class="config-field"><span>Image URL</span><input class="config-input" id="slider-image-url" value="<?= $e($slide['image'] ?? '') ?>"></label><label class="config-field"><span>Upload Image</span><input class="admin-file-input" id="slider-image-file" type="file" accept="image/*"></label><div class="settings-banner-preview mt-4"><div class="settings-banner-preview-media"><?php if (!empty($slide['image'])): ?><img src="<?= $e($slide['image']) ?>" alt="<?= $e($slide['title'] ?? 'Slider') ?>" loading="lazy"><?php endif; ?></div></div></section><button type="submit" class="btn btn-primary w-full">Save Slider <?= $sliderSlot ?></button></aside></form><?php else: ?><section class="admin-card mt-6 p-4 md:p-6"><div class="slider-card-grid"><?php for ($i = 0; $i < 2; $i++): $item = $slides[$i] ?? []; ?><article class="slider-card"><?php if (!empty($item['image'])): ?><img src="<?= $e($item['image']) ?>" alt="<?= $e($item['title'] ?? 'Slider') ?>"><?php endif; ?><div><span class="cms-pill cms-pill-blue">Hero slot <?= $i + 1 ?></span><h2 class="mt-3"><?= $e($item['title'] ?? 'Belum ada headline') ?></h2><p><?= $e($item['caption'] ?? 'Belum ada deskripsi.') ?></p></div><a class="cms-action edit" href="/admin/slider-add?slot=<?= $i + 1 ?>">Edit</a></article><?php endfor; ?></div></section><?php endif; ?>
<?php elseif (str_starts_with($page, 'why')): ?>
  <header class="cms-header slide-in"><div><p class="eyebrow">Admin CMS</p><h1 class="section-title mt-3"><?= $isWhyEditor ? 'Add Why Choose Us' : 'View Why Choose Us' ?></h1><p class="mt-4 max-w-2xl text-base leading-7 text-neutral-600">Konten edukasi masih berada pada fase prototipe, tetapi halaman ini tidak lagi merender kosong di browser.</p></div><a href="<?= $isWhyEditor ? '/admin/why-choose' : '/admin/why-choose-add' ?>" class="btn <?= $isWhyEditor ? 'btn-secondary' : 'btn-primary' ?>"><?= $isWhyEditor ? 'View All' : 'Add New' ?></a></header>
  <?php if ($isWhyEditor): ?><form class="editor-workspace compact mt-6" id="why-form"><main class="block-writing-surface"><div class="news-title-block" contenteditable="true" data-placeholder="Nama item edukasi..."></div><article class="news-body-block smaller" contenteditable="true" data-placeholder="Isi penjelasan singkat..."></article></main><aside class="editor-config-sidebar"><section class="config-card"><h2>Media</h2><label class="config-field"><span>Icon</span><input class="config-input" placeholder="thumb, globe, clock..."></label></section><button type="submit" class="btn btn-primary w-full">Submit Item</button></aside></form><?php else: ?><section class="admin-card mt-6 p-4 md:p-6"><div class="simple-card-grid"><?php foreach ([['What is GenBI?', 'Penjelasan singkat tentang komunitas Generasi Baru Indonesia.'], ['What is Inflation?', 'Materi edukasi inflasi dan stabilitas harga.'], ['What is QRIS?', 'Materi edukasi QRIS dan pembayaran digital.']] as [$title, $text]): ?><article class="simple-admin-card"><div class="meta">Educational card</div><h2><?= $e($title) ?></h2><p><?= $e($text) ?></p></article><?php endforeach; ?></div></section><?php endif; ?>
<?php elseif (str_starts_with($page, 'faq')): ?>
  <header class="cms-header slide-in"><div><p class="eyebrow">Admin CMS</p><h1 class="section-title mt-3"><?= $isFaqEditor ? 'Add FAQ' : 'View FAQs' ?></h1><p class="mt-4 max-w-2xl text-base leading-7 text-neutral-600">FAQ prototipe dirender langsung oleh server.</p></div><a href="<?= $isFaqEditor ? '/admin/faq' : '/admin/faq-add' ?>" class="btn <?= $isFaqEditor ? 'btn-secondary' : 'btn-primary' ?>"><?= $isFaqEditor ? 'View All' : 'Add New' ?></a></header>
  <?php if ($isFaqEditor): ?><form class="editor-workspace compact mt-6" id="faq-form"><main class="block-writing-surface"><div class="news-title-block" contenteditable="true" data-placeholder="Pertanyaan FAQ..."></div><article class="news-body-block smaller" contenteditable="true" data-placeholder="Tulis jawaban FAQ..."></article></main><aside class="editor-config-sidebar"><section class="config-card"><h2>Visibility</h2><label class="config-field"><span>Show on Home</span><select id="faq-show-home" class="config-input"><option>Yes</option><option>No</option></select></label></section><button type="submit" class="btn btn-primary w-full">Submit FAQ</button></aside></form><?php else: ?><section class="admin-card mt-6 p-5"><article class="simple-admin-card"><div class="meta">Show on home: Yes</div><h2>GenBI Provinsi Jambi</h2><p>Informasi umum tentang komunitas, kegiatan, dan anggota GenBI Jambi.</p></article></section><?php endif; ?>
<?php elseif (str_starts_with($page, 'social')): ?>
  <header class="cms-header slide-in"><div><p class="eyebrow">Admin CMS</p><h1 class="section-title mt-3">Social Media</h1><p class="mt-4 max-w-2xl text-base leading-7 text-neutral-600">Kanal sosial tersedia langsung dari respons server.</p></div><button id="save-social" class="btn btn-primary" type="button">Submit</button></header><section class="admin-card mt-6 p-5 md:p-7"><div class="grid max-w-3xl gap-4"><label class="config-field"><span>YouTube</span><input class="config-input" value="https://youtu.be/9fqrRMLTw6F"></label><label class="config-field"><span>Instagram</span><input class="config-input" value="https://www.instagram.com/genbi_jambi"></label><label class="config-field"><span>WhatsApp</span><input class="config-input" value="https://wa.me/6289627896750"></label></div></section>
<?php else: ?>
  <header class="cms-header slide-in"><div><p class="eyebrow">Page Editor</p><h1 class="section-title mt-3">Peta pengelolaan halaman.</h1><p class="mt-4 max-w-2xl text-base leading-7 text-neutral-600">Konfigurasi halaman publik yang aktif tersedia sebagai tautan server-side; data konten aktual dikelola oleh modul terkait.</p></div><a href="/admin/settings" class="btn btn-primary">Buka Settings</a></header><section class="admin-card mt-6 p-5 md:p-6"><div class="admin-responsive-table"><table class="cms-table"><thead><tr><th>Halaman / section</th><th>Sumber data</th><th>Aksi</th></tr></thead><tbody><tr><td>Beranda</td><td>Settings dan Page Home</td><td><a class="cms-action edit" href="/admin/settings">Settings</a></td></tr><tr><td>Kontak</td><td>Contact setting</td><td><a class="cms-action edit" href="/contact">Preview</a></td></tr><tr><td>Berita</td><td>News CMS</td><td><a class="cms-action edit" href="/admin/news">Kelola</a></td></tr><tr><td>Agenda</td><td>Agenda CMS</td><td><a class="cms-action edit" href="/admin/event">Kelola</a></td></tr><tr><td>Team</td><td>Team Member CMS</td><td><a class="cms-action edit" href="/admin/team-member">Kelola</a></td></tr></tbody></table></div></section>
<?php endif; ?>
</section>
